name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Run tests
      run: pytest 

    #-- Teams通知 --#
    # 成功
    - name: 'Teams Notification on Success'
      if: ${{ success() }}
      run: |
        MESSAGE="ジョブ詳細:  ${{ github.repository }} ComposerのGCSへのデプロイは成功しました。(コミットメッセージ: ${{ github.event.head_commit.message }} | 作成者: ${{ github.event.head_commit.author.name }} | タイムスタンプ: ${{ github.event.head_commit.timestamp }})"
        curl -X POST -H "Content-Type: application/json" -d "{\"@type\": \"MessageCard\",\"title\": \"デプロイ成功\",\"text\": \"$MESSAGE\"}" ${{ secrets.TEAMS_WEBHOOK_URL }}
      env:
        WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

    # 失敗
    - name: Run Python script
      if: ${{ failure() }}
      run: python utils/utility_funcs.py ${{ secrets.TEAMS_WEBHOOK_URL }} ['chaonan.wang@avantcorp.com'] # $(python utils/mention_members.py)
      env:
        WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

        




