name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Run tests
      run: pytest 

    #-- Teams通知 --#
    # 成功
    - name: 'Teams Notification on Success'
      uses: 'thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b'
      if: ${{ success() }}
      with:
        webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
        dry_run: True

    # 失敗
    - name: 'Teams Notification on Failure'
      uses: 'thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b'
      if: ${{ failure() }}
      with:
        webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
        dry_run: True
