name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Run tests
      run: pytest 

    #-- Teams通知 --#
    # 成功
    - name: 'Teams Notification on Success'
      if: ${{ failure() }}
      run: |
        MESSAGE="Hello Team! This is an important message."
        curl -X POST -H "Content-Type: application/json" -d "{\"@type\": \"MessageCard\",\"title\": \"GitHub Action Notification\",\"text\": \"$MESSAGE\",\"mentions\": {\"mentionType\": \"users\",\"mentionTarget\": [\"all\"]}}" ${{ secrets.TEAMS_WEBHOOK_URL }}
      env:
        WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

    # 失敗
    - name: 'Teams Notification on Failure'
      if: ${{ success() }}
      run: |
        MESSAGE="Hello Team! This is an important message."
        DATA={
            "type": "message",
            "attachments": [
                {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "type": "AdaptiveCard",
                    "body": [
                        {
                            "type": "TextBlock",
                            "size": "Medium",
                            "weight": "Bolder",
                            "text": "Sample Adaptive Card with User Mention"
                        },
                        {
                            "type": "TextBlock",
                            "text": "Hi <at>Adele UPN</at>, <at>Adele Microsoft Entra ID</at>"
                        }
                    ],
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "version": "1.0",
                    "msteams": {
                        "entities": [
                            {
                                "type": "mention",
                                "text": "<at>Adele UPN</at>",
                                "mentioned": {
                                  "id": "chaonan.wang@zdh.co.jp",
                                  "name": "chaonan_wang"
                                }
                              }
                        ]
                    }
                }
            }]
        }
        curl -X POST -H "Content-Type: application/json" -d "$DATA" ${{ secrets.TEAMS_WEBHOOK_URL }}
      env:
        WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}


