name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Run tests
      run: pytest 

    #-- Teams通知 --#
    # 成功
    - name: 'Teams Notification on Success'
      if: ${{ success() }}
      run: |
        MESSAGE=$(echo "Job Details: \nRepository: ${{ github.repository }}\nEvent path: ${{ github.event_path }}\nMessage: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nTimestamp: ${{ github.event.head_commit.timestamp }}" | sed 's/\n/<br>/g')
        curl -X POST -H "Content-Type: application/json" -d "{\"@type\": \"MessageCard\",\"title\": \"デプロイ成功\",\"text\": \"$MESSAGE\"}" ${{ secrets.TEAMS_WEBHOOK_URL }}
      env:
        WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

    # 失敗
    - name: 'Teams Notification on Failure'
      if: ${{ failure() }}
      run: |
        MESSAGE="Job Details: \nJob name: ${{ github.job }}\nWorkflow: ${{ github.workflow }}\nRun ID: ${{ github.run_id }}\nRepository: ${{ github.repository }}\nSHA: ${{ github.sha }}\nEvent name: ${{ github.event_name }}\nEvent path: ${{ github.event_path }}\nMessage: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nTimestamp: ${{ github.event.head_commit.timestamp }}"
        curl -X POST -H "Content-Type: application/json" -d "{\"@type\": \"MessageCard\",\"title\": \"デプロイ失敗\",\"text\": \"$MESSAGE\"}" ${{ secrets.TEAMS_WEBHOOK_URL }}
      env:
        WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}




